[theme]
name = "native"
[theme.overrides]
idle_bg = "#282c34"
idle_fg = "#abb2bf"
info_fg = "#56b6c2"
info_bg = "#282c34"
good_fg = "#98c379"
good_bg = "#282c34"
warning_fg = "#e5c07b"
warning_bg = "#282c34"
critical_fg = "#e06c75"
critical_bg = "#282c34"

[icons]
name = "none"
[icons.overrides]
music = "\uf886" # nf-mdi-music_note
music_next = "\uf9ac" # nf-mdi-skip_next
music_pause = "\uf8e3" # nf-mdi-pause
music_play = "\uf909" # nf-mdi-play
music_prev = "\uf9ad" # nf-mdi-skip_previous
net_up = "\uf077"
net_down = "\uf078"
update = "\uf8d4" # nf-mdi-package_up 
pomodoro = "\ue001" # nf-pom-pomodoro_done
pomodoro_break = "\uf0f4" # nf-fa-coffee
pomodoro_paused = "\uf04c" # nf-fa-pause
pomodoro_started = "\uf04b" # nf-fa-play
pomodoro_stopped = "\uf04d" # nf-fa-stop

[[block]]
block = "music"
#buttons = ["prev", "play", "next"]
dynamic_width = true
hide_when_empty = true
max_width = 40

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "networkmanager"
device_format = "{typename}"
on_click = "alacritty -t 'nmtui' -e nmtui"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
on_click = "alacritty -t 'htop' -e htop"

[[block]]
block = "cpu"
interval = 5
on_click = "alacritty -t 'htop' -e htop"

[[block]]
block = "temperature"
interval = 10
chip = "coretemp-isa-*"
format = "{average}"
collapsed = false

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "battery"
full_format = "{percentage}"
driver = "upower"
hide_missing = true

[[block]]
block = "time"
interval = 5
format = " %a %d/%m %I:%M %p"
icons_format = ""
