[theme]
name = "native"

[theme.overrides]

info_fg = "#86c1b9"
good_fg = "#a1b56c"
warning_fg = "#f7ca88"
critical_fg = "#ab4642"

[icons]
name = "material-nf"

[[block]]
block = "focused_window"
max_width = 50 
show_marks = "visible"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
max_width = 30

[[block]]
block = "pacman"
interval = 3600
aur_command = "paru -Qua"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
format = "{speed_up;K*b}{speed_down;K*b}"
on_click = "alacritty -t 'nmtui' -e nmtui"
interval = 5

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 5

[[block]]
block="backlight"

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "battery"
driver = "upower"

[[block]]
block = "time"
interval = 5
format = " %a %d/%m %R"
icons_format = ""
