[theme]
name = "native"

[theme.overrides]
idle_fg = "#abb2bf"
info_fg = "#11a8cd"
good_fg = "#a1b56c"
warning_fg = "#f7ca88"
critical_fg = "#ab4642"

[icons]
name = "none"
[icons.overrides]
music = "\uf886" # nf-mdi-music_note
music_next = "\uf9ac" # nf-mdi-skip_next
music_pause = "\uf8e3" # nf-mdi-pause
music_play = "\uf909" # nf-mdi-play
music_prev = "\uf9ad" # nf-mdi-skip_previous
net_up = "\uf077"
net_down = "\uf078"
update = "\uf8d4" # nf-mdi-package_up 
pomodoro = "\ue001" # nf-pom-pomodoro_done
pomodoro_break = "\uf0f4" # nf-fa-coffee
pomodoro_paused = "\uf04c" # nf-fa-pause
pomodoro_started = "\uf04b" # nf-fa-play
pomodoro_stopped = "\uf04d" # nf-fa-stop

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
dynamic_width = true
hide_when_empty = true
max_width = 30

[[block]]
block = "pomodoro"
notifier = "i3nag"

[[block]]
block = "pacman"
interval = 7200
format = "{both}"
critical_updates_regex = "(linux|linux-lts)"
aur_command = "paru -Qua"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
format = "{speed_up;K*b}{speed_down;K*b}"
on_click = "alacritty -t 'nmtui' -e nmtui"
interval = 5
hide_inactive = true

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
on_click = "alacritty -t 'htop' -e htop"

[[block]]
block = "cpu"
interval = 5
on_click = "alacritty -t 'htop' -e htop"

[[block]]
block = "temperature"
interval = 10
chip = "coretemp-isa-*"
format = "{average}"
collapsed = false

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "battery"
driver = "upower"

[[block]]
block = "time"
interval = 5
format = " %a %d/%m %I:%M %p"
icons_format = ""
