[theme]
name = "native"
[theme.overrides]

idle_bg = "#282c34"
idle_fg = "#abb2bf"
info_bg = "#282c34"
info_fg = "#56b6c2"
good_bg = "#282c34"
good_fg = "#98c379"
warning_bg = "#282c34"
warning_fg = "#e5c07b"
critical_bg = "#282c34"
critical_fg = "#e06c75"

[icons]
name = "none"
[icons.overrides]
music = "\uf886"
music_next = "\uf061"
music_pause = "\uf04c"
music_play = "\uf04b"
music_prev = "\uf060"
net_up = "\uf077"
net_down = "\uf078"
backlight_empty = "\uf5dd"
backlight_1 = "\uf5dd"
backlight_2 = "\uf5dd"
backlight_3 = "\uf5dd"
backlight_4 = "\uf5dd"
backlight_5 = "\uf5dd"
backlight_6 = "\uf5dd"
backlight_7 = "\uf5de"
backlight_8 = "\uf5de"
backlight_9 = "\uf5de"
backlight_10 = "\uf5de"
backlight_11 = "\uf5de"
backlight_12 = "\uf5de"
backlight_13 = "\uf5df"
backlight_full = "\uf5df"


[[block]]
block = "music"
buttons = ["prev", "play", "next"]
max_width = 30

[[block]]
block = "pacman"
interval = 3600
aur_command = "paru -Qua"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
format = "{speed_up;K*b}{speed_down;K*b}"
on_click = "alacritty -t 'nmtui' -e nmtui"
interval = 5

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 5

[[block]]
block="backlight"

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "battery"
interval = 10
format = "{percentage}"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
icons_format = " "
